hal: fix compiling
* Use libtinycompress_vendor instead of libtinycompress as shared lib
* Add -DUSE_VENDOR_EXTN flag to LOCAL_CFLAGS

Fix

hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:2689:17: error: implicit declaration of function 'compress_set_next_track_param' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                compress_set_next_track_param(out->compr, &(out->compr_config.codec->options));

Test: Run mka audio.primary.msm8996
Test: compiles fine without errors

Signed-off-by: Marco Zanin (B--B) <mrczn.bb@gmail.com>